// Regenerates src/og/fonts.data.ts from the vendored Geist Mono woff files.
// Run: bun run scripts/gen-og-fonts.ts
//
// The OG renderer (satori) needs raw font bytes. Reading them from disk at runtime
// doesn't survive the Nitro/Vercel server build (Vite drops new URL(import.meta.url)
// assets and a fs path isn't traced into the function), so the bytes are embedded
// as base64 ESM strings instead — always bundled, no fs/tracing at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const FONTS = [
  ["w400", "geist-mono-latin-400-normal.woff"],
  ["w600", "geist-mono-latin-600-normal.woff"],
  ["w700", "geist-mono-latin-700-normal.woff"],
] as const;

const dir = join(import.meta.dir, "..", "src", "og", "fonts");

let out =
  "// GENERATED by scripts/gen-og-fonts.ts — do not edit by hand.\n" +
  "// Geist Mono woff bytes (base64) embedded for satori OG rendering.\n\n";
for (const [name, file] of FONTS) {
  const b64 = readFileSync(join(dir, file)).toString("base64");
  out += `export const ${name} = "${b64}";\n`;
}

const target = join(import.meta.dir, "..", "src", "og", "fonts.data.ts");
writeFileSync(target, out);
console.log(`wrote ${target} (${out.length} bytes)`);
