/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSymbolRouteImport } from './routes/t.$symbol'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiCallsIndexRouteImport } from './routes/api/calls-index'
import { Route as CHandleIndexRouteImport } from './routes/c.$handle.index'
import { Route as ApiPricesSymbolRouteImport } from './routes/api/prices.$symbol'
import { Route as ApiDatasetHandleRouteImport } from './routes/api/dataset.$handle'
import { Route as CHandleTickerSymbolRouteImport } from './routes/c.$handle.ticker.$symbol'
import { Route as ApiOgCHandleRevRouteImport } from './routes/api/og/c.$handle.$rev'
import { Route as ApiOgTHandleSymbolRevRouteImport } from './routes/api/og/t.$handle.$symbol.$rev'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSymbolRoute = TSymbolRouteImport.update({
  id: '/t/$symbol',
  path: '/t/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsIndexRoute = ApiCallsIndexRouteImport.update({
  id: '/api/calls-index',
  path: '/api/calls-index',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleIndexRoute = CHandleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CHandleRoute,
} as any)
const ApiPricesSymbolRoute = ApiPricesSymbolRouteImport.update({
  id: '/api/prices/$symbol',
  path: '/api/prices/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetHandleRoute = ApiDatasetHandleRouteImport.update({
  id: '/api/dataset/$handle',
  path: '/api/dataset/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleTickerSymbolRoute = CHandleTickerSymbolRouteImport.update({
  id: '/ticker/$symbol',
  path: '/ticker/$symbol',
  getParentRoute: () => CHandleRoute,
} as any)
const ApiOgCHandleRevRoute = ApiOgCHandleRevRouteImport.update({
  id: '/api/og/c/$handle/$rev',
  path: '/api/og/c/$handle/$rev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgTHandleSymbolRevRoute = ApiOgTHandleSymbolRevRouteImport.update({
  id: '/api/og/t/$handle/$symbol/$rev',
  path: '/api/og/t/$handle/$symbol/$rev',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/calls-index': typeof ApiCallsIndexRoute
  '/api/report': typeof ApiReportRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/c/$handle': typeof CHandleRouteWithChildren
  '/t/$symbol': typeof TSymbolRoute
  '/api/dataset/$handle': typeof ApiDatasetHandleRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/c/$handle/': typeof CHandleIndexRoute
  '/c/$handle/ticker/$symbol': typeof CHandleTickerSymbolRoute
  '/api/og/c/$handle/$rev': typeof ApiOgCHandleRevRoute
  '/api/og/t/$handle/$symbol/$rev': typeof ApiOgTHandleSymbolRevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/calls-index': typeof ApiCallsIndexRoute
  '/api/report': typeof ApiReportRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/t/$symbol': typeof TSymbolRoute
  '/api/dataset/$handle': typeof ApiDatasetHandleRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/c/$handle': typeof CHandleIndexRoute
  '/c/$handle/ticker/$symbol': typeof CHandleTickerSymbolRoute
  '/api/og/c/$handle/$rev': typeof ApiOgCHandleRevRoute
  '/api/og/t/$handle/$symbol/$rev': typeof ApiOgTHandleSymbolRevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/calls-index': typeof ApiCallsIndexRoute
  '/api/report': typeof ApiReportRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/c/$handle': typeof CHandleRouteWithChildren
  '/t/$symbol': typeof TSymbolRoute
  '/api/dataset/$handle': typeof ApiDatasetHandleRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/c/$handle/': typeof CHandleIndexRoute
  '/c/$handle/ticker/$symbol': typeof CHandleTickerSymbolRoute
  '/api/og/c/$handle/$rev': typeof ApiOgCHandleRevRoute
  '/api/og/t/$handle/$symbol/$rev': typeof ApiOgTHandleSymbolRevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/sitemap.xml'
    | '/api/calls-index'
    | '/api/report'
    | '/api/revalidate'
    | '/c/$handle'
    | '/t/$symbol'
    | '/api/dataset/$handle'
    | '/api/prices/$symbol'
    | '/c/$handle/'
    | '/c/$handle/ticker/$symbol'
    | '/api/og/c/$handle/$rev'
    | '/api/og/t/$handle/$symbol/$rev'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/sitemap.xml'
    | '/api/calls-index'
    | '/api/report'
    | '/api/revalidate'
    | '/t/$symbol'
    | '/api/dataset/$handle'
    | '/api/prices/$symbol'
    | '/c/$handle'
    | '/c/$handle/ticker/$symbol'
    | '/api/og/c/$handle/$rev'
    | '/api/og/t/$handle/$symbol/$rev'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/sitemap.xml'
    | '/api/calls-index'
    | '/api/report'
    | '/api/revalidate'
    | '/c/$handle'
    | '/t/$symbol'
    | '/api/dataset/$handle'
    | '/api/prices/$symbol'
    | '/c/$handle/'
    | '/c/$handle/ticker/$symbol'
    | '/api/og/c/$handle/$rev'
    | '/api/og/t/$handle/$symbol/$rev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCallsIndexRoute: typeof ApiCallsIndexRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  CHandleRoute: typeof CHandleRouteWithChildren
  TSymbolRoute: typeof TSymbolRoute
  ApiDatasetHandleRoute: typeof ApiDatasetHandleRoute
  ApiPricesSymbolRoute: typeof ApiPricesSymbolRoute
  ApiOgCHandleRevRoute: typeof ApiOgCHandleRevRoute
  ApiOgTHandleSymbolRevRoute: typeof ApiOgTHandleSymbolRevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$symbol': {
      id: '/t/$symbol'
      path: '/t/$symbol'
      fullPath: '/t/$symbol'
      preLoaderRoute: typeof TSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls-index': {
      id: '/api/calls-index'
      path: '/api/calls-index'
      fullPath: '/api/calls-index'
      preLoaderRoute: typeof ApiCallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle/': {
      id: '/c/$handle/'
      path: '/'
      fullPath: '/c/$handle/'
      preLoaderRoute: typeof CHandleIndexRouteImport
      parentRoute: typeof CHandleRoute
    }
    '/api/prices/$symbol': {
      id: '/api/prices/$symbol'
      path: '/api/prices/$symbol'
      fullPath: '/api/prices/$symbol'
      preLoaderRoute: typeof ApiPricesSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dataset/$handle': {
      id: '/api/dataset/$handle'
      path: '/api/dataset/$handle'
      fullPath: '/api/dataset/$handle'
      preLoaderRoute: typeof ApiDatasetHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle/ticker/$symbol': {
      id: '/c/$handle/ticker/$symbol'
      path: '/ticker/$symbol'
      fullPath: '/c/$handle/ticker/$symbol'
      preLoaderRoute: typeof CHandleTickerSymbolRouteImport
      parentRoute: typeof CHandleRoute
    }
    '/api/og/c/$handle/$rev': {
      id: '/api/og/c/$handle/$rev'
      path: '/api/og/c/$handle/$rev'
      fullPath: '/api/og/c/$handle/$rev'
      preLoaderRoute: typeof ApiOgCHandleRevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/t/$handle/$symbol/$rev': {
      id: '/api/og/t/$handle/$symbol/$rev'
      path: '/api/og/t/$handle/$symbol/$rev'
      fullPath: '/api/og/t/$handle/$symbol/$rev'
      preLoaderRoute: typeof ApiOgTHandleSymbolRevRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CHandleRouteChildren {
  CHandleIndexRoute: typeof CHandleIndexRoute
  CHandleTickerSymbolRoute: typeof CHandleTickerSymbolRoute
}

const CHandleRouteChildren: CHandleRouteChildren = {
  CHandleIndexRoute: CHandleIndexRoute,
  CHandleTickerSymbolRoute: CHandleTickerSymbolRoute,
}

const CHandleRouteWithChildren =
  CHandleRoute._addFileChildren(CHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCallsIndexRoute: ApiCallsIndexRoute,
  ApiReportRoute: ApiReportRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  CHandleRoute: CHandleRouteWithChildren,
  TSymbolRoute: TSymbolRoute,
  ApiDatasetHandleRoute: ApiDatasetHandleRoute,
  ApiPricesSymbolRoute: ApiPricesSymbolRoute,
  ApiOgCHandleRevRoute: ApiOgCHandleRevRoute,
  ApiOgTHandleSymbolRevRoute: ApiOgTHandleSymbolRevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
