/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as CHandleTickerSymbolRouteImport } from './routes/c.$handle.ticker.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleTickerSymbolRoute = CHandleTickerSymbolRouteImport.update({
  id: '/ticker/$symbol',
  path: '/ticker/$symbol',
  getParentRoute: () => CHandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$handle': typeof CHandleRouteWithChildren
  '/c/$handle/ticker/$symbol': typeof CHandleTickerSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$handle': typeof CHandleRouteWithChildren
  '/c/$handle/ticker/$symbol': typeof CHandleTickerSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$handle': typeof CHandleRouteWithChildren
  '/c/$handle/ticker/$symbol': typeof CHandleTickerSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$handle' | '/c/$handle/ticker/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$handle' | '/c/$handle/ticker/$symbol'
  id: '__root__' | '/' | '/c/$handle' | '/c/$handle/ticker/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CHandleRoute: typeof CHandleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle/ticker/$symbol': {
      id: '/c/$handle/ticker/$symbol'
      path: '/ticker/$symbol'
      fullPath: '/c/$handle/ticker/$symbol'
      preLoaderRoute: typeof CHandleTickerSymbolRouteImport
      parentRoute: typeof CHandleRoute
    }
  }
}

interface CHandleRouteChildren {
  CHandleTickerSymbolRoute: typeof CHandleTickerSymbolRoute
}

const CHandleRouteChildren: CHandleRouteChildren = {
  CHandleTickerSymbolRoute: CHandleTickerSymbolRoute,
}

const CHandleRouteWithChildren =
  CHandleRoute._addFileChildren(CHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CHandleRoute: CHandleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
